name: Docs
on:
  push:
    branches:
      - master
jobs:
  build_and_publish:
    name: Build and publish Docs
    runs-on: ubuntu-latest
    if: github.repository == 'PHPMailer/PHPMailer'
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Build Docs
        uses: ./.github/actions/build-docs
      - name: Publish Docs to gh-pages
        uses: maxheld83/ghpages@v0.2.1
        env:
          BUILD_DIR: docs/
          GH_PAT: ${{ secrets.GH_PAT }}
